version: '3'
services:
  app:
    build: .
    links: 
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 6969
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
